%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/aneira/lalo/data/suj9/sofey_20150630.151708.864330/vision.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/09/28 20:50:30

%% Initialize variables.
filename = '/Users/aneira/lalo/data/suj9/sofey_20150630.151708.864330/vision.csv';
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: text (%s)
%   column9: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%f%f%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', true);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
timestamp = dataArray{:, 1};
frame_number = dataArray{:, 2};
gaze_x = dataArray{:, 3};
gaze_y = dataArray{:, 4};
pupil_axis1 = dataArray{:, 5};
pupil_axis2 = dataArray{:, 6};
pupil_area = dataArray{:, 7};
saccade = dataArray{:, 8};
blink = dataArray{:, 9};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;
